/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Control.LaporanDAO;
import Control.LaporanDAOImpl;
import Model.Daerah;
import Model.Laporan;
import Model.Users;
import Util.HibernateUtil;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author User
 */
public class Lapor extends javax.swing.JFrame {
    private int userId;
    private byte[] fotoBytes;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lapor.class.getName());

    /**
     * Creates new form Lapor
     */
    public Lapor() {
        initComponents();
    }
    
    Lapor(int userId) {
    initComponents();
    this.userId = userId;
    loadKecamatan();
    }

    private void loadKecamatan() {
    try {
            java.sql.Connection conn = Koneksi.Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery("SELECT id_daerah, kecamatan FROM daerah");

            jComboBox1.removeAllItems();
            while (rs.next()) {
                jComboBox1.addItem(rs.getInt("id_daerah") + " - " + rs.getString("kecamatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load kecamatan: " + e.getMessage());
        }}
    private int getSelectedDaerahId() {
        if (jComboBox1.getSelectedItem() == null) return -1;
        String selected = jComboBox1.getSelectedItem().toString();
        return Integer.parseInt(selected.split(" - ")[0]);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnKirim = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAFile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tinggi Air (Cm)");

        txtTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinggiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Lokasi");

        txtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiActionPerformed(evt);
            }
        });

        btnUpload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpload.setText("Upload Foto");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Foto Bukti (Max 16MB)");

        btnKirim.setBackground(new java.awt.Color(51, 102, 255));
        btnKirim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKirim.setForeground(new java.awt.Color(255, 255, 255));
        btnKirim.setText("Kirim");
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Kecamatan");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 54)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("LAPOR BANJIR");

        txtAFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUpload)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAFile, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(txtTinggi)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKirim))
                            .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 420, 460));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/BG BIRU.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 701, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinggiActionPerformed

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Pilih Foto Bukti");
chooser.addChoosableFileFilter(
    new javax.swing.filechooser.FileNameExtensionFilter("Gambar (*.jpg, *.jpeg, *.png)", "jpg", "jpeg", "png")
);
chooser.setFileFilter(chooser.getChoosableFileFilters()[0]);

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            java.io.File file = chooser.getSelectedFile();

            long maxSize = 16 * 1024 * 1024; 

            // Validasi ukuran file
            if (file.length() > maxSize) {
                JOptionPane.showMessageDialog(this, 
                    "Ukuran file terlalu besar!.", 
                    "File Terlalu Besar", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
        java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(file);
        if (img == null) {
            JOptionPane.showMessageDialog(this,
                "File bukan gambar yang valid!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "File tidak dapat dibaca sebagai gambar!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

            try (java.io.FileInputStream fis = new java.io.FileInputStream(file)) {
                fotoBytes = fis.readAllBytes();
                txtAFile.setText(file.getAbsolutePath());
                JOptionPane.showMessageDialog(this, "Foto berhasil dipilih: " + file.getName());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal mengungah foto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        if (txtTinggi.getText().isBlank() || txtLokasi.getText().isBlank()){
        JOptionPane.showMessageDialog(this, "Tinggi air dan lokasi harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        int idDaerah = getSelectedDaerahId();
        if (idDaerah == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kecamatan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double tinggiAir = Double.parseDouble(txtTinggi.getText());
            String lokasi = txtLokasi.getText();
            Daerah daerah = getDaerahById(idDaerah);
            Users user = getUserById(userId);

            if (tinggiAir > 150) {
                JOptionPane.showMessageDialog(this, "Tinggi air tidak masuk akal");
            return;
            }
            if (lokasi.isBlank()) {
            JOptionPane.showMessageDialog(this, "Lokasi wajib diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
            if (lokasi.length() > 500) {
            JOptionPane.showMessageDialog(this, "Lokasi terlalu panjang");
            return;
            }
            if (!lokasi.matches(".*[a-zA-Z].*")) {
                JOptionPane.showMessageDialog(this, "Lokasi harus mengandung huruf!", "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            if (!lokasi.matches("[a-zA-Z0-9 .,'/-]+")) {
                JOptionPane.showMessageDialog(this, "Lokasi hanya boleh berisi huruf, angka, spasi, titik(.), koma(,), strip(-), apostrof(') atau garis miring(/)", "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
             return;
            }
            if (daerah == null) {
                JOptionPane.showMessageDialog(this, "Daerah tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (user == null) {
                JOptionPane.showMessageDialog(this, "User tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Laporan laporan = new Laporan();
            laporan.setTanggalLaporan(LocalDate.now());
            laporan.setTinggiAir((float) tinggiAir);
            laporan.setLokasi(lokasi);
            laporan.setFotoBukti(fotoBytes);
            laporan.setStatus(Laporan.StatusBanjir.MASIH_BANJIR);
            laporan.setDaerah(daerah);
            laporan.setUser(user);

            LaporanDAO dao = new LaporanDAOImpl();
            dao.tambah(laporan);

            JOptionPane.showMessageDialog(this, "Laporan berhasil dikirim!");
            resetForm();

            LaporanU laporanU = new LaporanU(userId);
            laporanU.setVisible(true);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tinggi air harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        }

        private Daerah getDaerahById(int idDaerah) {
            try (Session session = HibernateUtil.getSessionFactory().openSession()) {
                return session.get(Daerah.class, idDaerah);
            }
        }

        private Users getUserById(int idUser) {
            try (Session session = HibernateUtil.getSessionFactory().openSession()) {
                return session.get(Users.class, idUser);
            }
        }

        private void resetForm() {
            txtTinggi.setText("");
            txtLokasi.setText("");
            txtAFile.setText("");
            fotoBytes = null;
            if (jComboBox1.getItemCount() > 0) jComboBox1.setSelectedIndex(0);

    }//GEN-LAST:event_btnKirimActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       LaporanU Laporan = new LaporanU(userId);
       Laporan.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtAFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKirim;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAFile;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
