/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class LaporanU extends javax.swing.JFrame {
    private int userId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanU.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public LaporanU() {
        initComponents();
    }
    public LaporanU(int userId) {
        initComponents();
        this.userId = userId;
        loadLaporan();
    }
    private String formatStatus(String status) {
    if (status == null) return "";
    return status.toLowerCase()
                 .replace("_", " ");
    }
    private void loadLaporan() {
    try {
        Connection conn = Koneksi.Koneksi.getConnection();
        String sql = "SELECT tanggal_laporan, tinggi_air, lokasi, "
                   + "d.kecamatan, u.nama_lengkap, status_banjir, foto_bukti "
                   + "FROM laporan l "
                   + "JOIN users u ON l.id_user = u.id_user "
                   + "JOIN daerah d ON l.id_daerah = d.id_daerah "
                   + "ORDER BY l.id_laporan DESC";

        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Tanggal", "Nama Pelapor", "Kecamatan", "Tinggi Air(cm)", "Lokasi", "Status", "Foto Bukti"}, 0
        ){
    @Override
    public boolean isCellEditable(int row, int column) {
        return column == 6;
    }
};
        while (rs.next()) {
            byte[] fotoBytes = rs.getBytes("foto_bukti");
            model.addRow(new Object[]{
                rs.getString("tanggal_laporan"),
                rs.getString("nama_lengkap"),
                rs.getString("kecamatan"),
                rs.getDouble("tinggi_air"),
                rs.getString("lokasi"),
                formatStatus(rs.getString("status_banjir")),
                fotoBytes
            });
        }

        tblLaporan.setModel(model);
        tblLaporan.setRowSelectionAllowed(true);
        tblLaporan.getColumnModel().getColumn(6).setCellRenderer(new ButtonRenderer());
        tblLaporan.getColumnModel().getColumn(6).setCellEditor(new ButtonEditor(new JCheckBox(), 6));
        tblLaporan.getTableHeader().setReorderingAllowed(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        e.printStackTrace();
    }
    ((DefaultTableModel) tblLaporan.getModel()).fireTableDataChanged();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        btnTindak = new javax.swing.JButton();
        btnKembali1 = new javax.swing.JButton();
        btnLapor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        tblLaporan.setRowHeight(30);
        jScrollPane1.setViewportView(tblLaporan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 760, 370));

        btnTindak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTindak.setText("Lihat Tindak Lanjut");
        btnTindak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTindakActionPerformed(evt);
            }
        });
        jPanel1.add(btnTindak, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 170, 35));

        btnKembali1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali1.setText("Kembali");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 35));

        btnLapor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLapor.setText("Buat Laporan");
        btnLapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporActionPerformed(evt);
            }
        });
        jPanel1.add(btnLapor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 130, 35));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laporan Banjir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lihat daerah mana saja yang mengalami banjir");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/BG BIRU.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTindakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTindakActionPerformed
        TindakU Tindak = new TindakU(userId);
        Tindak.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTindakActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        MenuUser MenuUser = new MenuUser(userId);
        MenuUser.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void btnLaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporActionPerformed
        Lapor Lapor = new Lapor(userId);
        Lapor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLaporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnLapor;
    private javax.swing.JButton btnTindak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
