/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.Laporan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author User
 */
public class LaporanA extends javax.swing.JFrame {
    private int userId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanA.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public LaporanA() {
        initComponents();
        loadLaporan();
        setupTableClick();
    }
    public LaporanA(int userId) {
        initComponents();
        this.userId = userId;
        loadLaporan();
        setupTableClick();
    }
    private void setupTableClick() {
    tblLaporan.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int row = tblLaporan.getSelectedRow();
            if (row >= 0) {
                txtID.setText(tblLaporan.getValueAt(row, 0).toString());
            }
        }
    });
}
    private String formatStatus(String status) {
    if (status == null) return "";
    return status.toLowerCase()
                 .replace("_", " ");
    }
    private void loadLaporan() {
    try {
        Connection conn = Koneksi.Koneksi.getConnection();
        String sql = "SELECT id_laporan, tanggal_laporan, tinggi_air, lokasi, "
                   + "d.kecamatan, u.nama_lengkap, status_banjir,foto_bukti "
                   + "FROM laporan l "
                   + "JOIN users u ON l.id_user = u.id_user "
                   + "JOIN daerah d ON l.id_daerah = d.id_daerah "
                   + "ORDER BY l.id_laporan DESC";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Tanggal", "Nama Pelapor", "Kecamatan", "Tinggi Air(cm)", "Lokasi", "Status","Foto Bukti"}, 0
        ){
    @Override
    public boolean isCellEditable(int row, int column) {
        return column == 7 ;
    }
};

        while (rs.next()) {
            byte[] fotoBytes = rs.getBytes("foto_bukti");
            Object fotoCell = (fotoBytes != null && fotoBytes.length > 0)
                    ? fotoBytes
                    : "Tidak Ada";
            model.addRow(new Object[]{
                rs.getInt("id_laporan"),
                rs.getString("tanggal_laporan"),
                rs.getString("nama_lengkap"),
                rs.getString("kecamatan"),
                rs.getDouble("tinggi_air"),
                rs.getString("lokasi"),
                formatStatus(rs.getString("status_banjir")),
                fotoCell
            });
        }

        tblLaporan.setModel(model);
        tblLaporan.setRowHeight(35);
        tblLaporan.getColumnModel().getColumn(7).setCellRenderer(new ButtonRenderer());
        tblLaporan.getColumnModel().getColumn(7).setCellEditor(new ButtonEditor(new JCheckBox(), 7));
        tblLaporan.getTableHeader().setReorderingAllowed(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTindak = new javax.swing.JButton();
        btnKembali1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblLaporan.setRowHeight(30);
        jScrollPane1.setViewportView(tblLaporan);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("ID Laporan");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setText("Ubah Status");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 760, 420));

        btnTindak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTindak.setLabel("Tindak Lanjut");
        btnTindak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTindakActionPerformed(evt);
            }
        });
        jPanel1.add(btnTindak, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 120, 35));

        btnKembali1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali1.setText("Kembali");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 35));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KELOLA LAPORAN BANJIR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 600, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/BG BIRU.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTindakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTindakActionPerformed
        TindakA tindakA = new TindakA(this.userId);
        tindakA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTindakActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        MenuAdmin MenuAdmin = new MenuAdmin();
        MenuAdmin.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
         String idText = txtID.getText();
    if (idText.isBlank()) {
        JOptionPane.showMessageDialog(this, "Pilih laporan terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int idLaporan = Integer.parseInt(idText);

    try (Session session = Util.HibernateUtil.getSessionFactory().openSession()) {
        Transaction tx = session.beginTransaction();
        Model.Laporan laporan = session.get(Model.Laporan.class, idLaporan);
        if (laporan != null) {
            // Toggle status banjir
            if (laporan.getStatus() == Laporan.StatusBanjir.MASIH_BANJIR) {
                laporan.setStatus(Laporan.StatusBanjir.SUDAH_SURUT);
            } else {
                laporan.setStatus(Laporan.StatusBanjir.MASIH_BANJIR);
            }
            session.merge(laporan);
            tx.commit();
            JOptionPane.showMessageDialog(this, "Status laporan berhasil diubah!");
            loadLaporan(); // refresh tabel
        } else {
            JOptionPane.showMessageDialog(this, "Laporan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mengubah status: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         String idText = txtID.getText();
    if (idText.isBlank()) {
        JOptionPane.showMessageDialog(this, "Pilih laporan terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int idLaporan = Integer.parseInt(idText);

    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus laporan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    try (Session session = Util.HibernateUtil.getSessionFactory().openSession()) {
        Transaction tx = session.beginTransaction();
        Model.Laporan laporan = session.get(Model.Laporan.class, idLaporan);
        if (laporan != null) {
            session.remove(laporan);
            tx.commit();
            JOptionPane.showMessageDialog(this, "Laporan berhasil dihapus!");
            loadLaporan(); // refresh tabel
        } else {
            JOptionPane.showMessageDialog(this, "Laporan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {

    Throwable cause = e.getCause();
    while (cause != null) {
        if (cause instanceof java.sql.SQLIntegrityConstraintViolationException) {
            JOptionPane.showMessageDialog(this,
                "Laporan ini memiliki tindak lanjut dan tidak bisa dihapus!",
                "Tidak Bisa Dihapus",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        cause = cause.getCause();
    }

    JOptionPane.showMessageDialog(this,
        "Gagal menghapus laporan: " + e.getMessage(),
        "Error",
        JOptionPane.ERROR_MESSAGE);
    
    e.printStackTrace();
}
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnTindak;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaporan;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
