/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TindakA extends javax.swing.JFrame {
    private int userId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TindakA.class.getName());
    

    /**
     * Creates new form TindakU
     */
    public TindakA() {
        initComponents();
        loadTindakLanjut();
        addTableListener();
    }

    TindakA(int userId) {
        initComponents();
        this.userId = userId;
        loadTindakLanjut();
        addTableListener();
    }
    
     private void addTableListener() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                    int row = jTable1.getSelectedRow();
                    txtIDTindak.setText(jTable1.getValueAt(row, 0).toString());
                    txtIDLaporan.setText(jTable1.getValueAt(row, 1).toString());
                    txtBentuk.setText(jTable1.getValueAt(row, 6).toString());
                }
            }
        });
     }
    
    
      private void loadTindakLanjut() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID Tindak", "ID Laporan", "Tanggal Laporan", "Lokasi",
                         "Tanggal Tindak", "Status", "Penanganan"}, 0
        ){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
        try (Connection conn = Koneksi.Koneksi.getConnection();
             PreparedStatement pst = conn.prepareStatement(
                 "SELECT t.id_tindak, l.id_laporan, l.tanggal_laporan, l.lokasi, " +
                 "t.tanggal_tindak, t.status, t.bentuk_penanganan " +
                 "FROM tindak_lanjut t LEFT JOIN laporan l ON t.id_laporan = l.id_laporan " +
                 "ORDER BY t.tanggal_tindak DESC");
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_tindak"),
                    rs.getInt("id_laporan"),
                    rs.getDate("tanggal_laporan"),
                    rs.getString("lokasi"),
                    rs.getDate("tanggal_tindak"),
                    rs.getString("status"),
                    rs.getString("bentuk_penanganan")
                });
            }
            jTable1.setModel(model);
            jTable1.getTableHeader().setReorderingAllowed(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtIDTindak = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIDLaporan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBentuk = new javax.swing.JTextField();
        btnPerbarui = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnKembali1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/Logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TINDAK LANJUT LAPORAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 590, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("ID Tindak Lanjut");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(txtIDTindak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("ID Laporan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));
        jPanel2.add(txtIDLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Bentuk Penanganan");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel2.add(txtBentuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 35));

        btnPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPerbarui.setText("Perbarui");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });
        jPanel2.add(btnPerbarui, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 100, 35));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 35));

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 100, 35));

        btnStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStatus.setText("Ubah Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        jPanel2.add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 35));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 745, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 760, 430));

        btnKembali1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali1.setText("Kembali");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/BG BIRU.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        LaporanA Laporan = new LaporanA(userId);
        Laporan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
        String idText = txtIDTindak.getText().trim();
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    try {
        int idTindak = Integer.parseInt(idText);

        Connection conn = Koneksi.Koneksi.getConnection();

        // Cek apakah id_tindak ada di DB
        PreparedStatement cek = conn.prepareStatement("SELECT id_tindak FROM tindak_lanjut WHERE id_tindak = ?");
        cek.setInt(1, idTindak);
        ResultSet rs = cek.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "ID Tindak Lanjut tidak ditemukan!");
            conn.close();
            return;
        }

        String bentuk = txtBentuk.getText().trim();
        if (bentuk.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bentuk penanganan wajib diisi!");
            conn.close();
            return;
        }

        String sql = "UPDATE tindak_lanjut SET id_laporan=?, tanggal_tindak=?, bentuk_penanganan=? WHERE id_tindak=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(txtIDLaporan.getText()));
        pst.setDate(2, java.sql.Date.valueOf(java.time.LocalDate.now()));
        pst.setString(3, bentuk);
        pst.setInt(4, idTindak);
        pst.executeUpdate();

        conn.close();
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui ✅");
        loadTindakLanjut();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui: " + e.getMessage());
    }
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        try {
    Connection conn = Koneksi.Koneksi.getConnection();

    String currentStatus = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();

    String newStatus = currentStatus.equals("SELESAI") ? "DIPROSES" : "SELESAI";

    String sql = "UPDATE tindak_lanjut SET status=? WHERE id_tindak=?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, newStatus);
    pst.setInt(2, Integer.parseInt(txtIDTindak.getText()));
    pst.executeUpdate();
    conn.close();

    JOptionPane.showMessageDialog(this, "Status berhasil diubah");
    loadTindakLanjut();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal mengubah status: " + e.getMessage());
}
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    try {
    // === VALIDASI ID Laporan ===
    String idText = txtIDLaporan.getText().trim();
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Laporan wajib diisi!");
        return;
    }

    int idLaporan;
    try {
        idLaporan = Integer.parseInt(idText);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "ID Laporan harus berupa angka!");
        return;
    }

    Connection conn = Koneksi.Koneksi.getConnection();
    PreparedStatement cek = conn.prepareStatement("SELECT id_laporan FROM laporan WHERE id_laporan = ?");
    cek.setInt(1, idLaporan);
    ResultSet rs = cek.executeQuery();
    if (!rs.next()) {
        JOptionPane.showMessageDialog(this, "ID Laporan tidak ditemukan!");
        conn.close();
        return;
    }

    String bentuk = txtBentuk.getText().trim();
    if (bentuk.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Bentuk penanganan wajib diisi!");
        conn.close();
        return;
    }
        // Minimal 5 huruf (mengabaikan angka dan spasi)
    if (bentuk.replaceAll("[^a-zA-Z]", "").length() < 5) {
        JOptionPane.showMessageDialog(this, 
            "Bentuk penanganan harus mengandung minimal 5 huruf!",
            "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
        conn.close();
        return;
    }

    // Boleh huruf, angka, spasi, dan tanda baca ringan
    if (!bentuk.matches("[a-zA-Z0-9 .,!?()'-]+")) {
        JOptionPane.showMessageDialog(this,
            "Bentuk penanganan hanya boleh berisi huruf, angka, spasi, dan tanda baca dasar!",
            "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
        conn.close();
        return;
    }

    if (bentuk.length() > 200) {
        JOptionPane.showMessageDialog(this, "Bentuk penanganan terlalu panjang (maksimal 200 karakter)!");
        conn.close();
        return;
    }

    String sql = "INSERT INTO tindak_lanjut (id_laporan, tanggal_tindak, status, bentuk_penanganan) VALUES (?, ?, ?, ?)";
    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setInt(1, idLaporan);
    pst.setDate(2, java.sql.Date.valueOf(java.time.LocalDate.now()));
    pst.setString(3, "DIPROSES");
    pst.setString(4, bentuk);

    pst.executeUpdate();
    conn.close();

    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
    loadTindakLanjut();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal menambah data: " + e.getMessage());
}
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String idText = txtIDTindak.getText().trim();
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        int idTindak = Integer.parseInt(idText);
        Connection conn = Koneksi.Koneksi.getConnection();

        // Cek apakah data ada dulu
        PreparedStatement cek = conn.prepareStatement("SELECT id_tindak FROM tindak_lanjut WHERE id_tindak=?");
        cek.setInt(1, idTindak);
        ResultSet rs = cek.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "ID Tindak tidak ditemukan!");
            conn.close();
            return;
        }

        PreparedStatement pst = conn.prepareStatement("DELETE FROM tindak_lanjut WHERE id_tindak=?");
        pst.setInt(1, idTindak);
        pst.executeUpdate();

        conn.close();
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus ✅");
        loadTindakLanjut();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBentuk;
    private javax.swing.JTextField txtIDLaporan;
    private javax.swing.JTextField txtIDTindak;
    // End of variables declaration//GEN-END:variables
}
